apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: oppfolgingsplan-lps-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: oppfolgingsplan-lps/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: oppfolgingsplan-lps/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - https://demo.ekstern.dev.nav.no/oppfolgingsplan-lps
  envFrom:
    - secret: lps-oppfolgingsplan-mottak-secrets
  accessPolicy:
    outbound:
      rules:
        - application: lps-oppfolgingsplan-mottak
