name: "Build and deploy"

on:
  push:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - uses: navikt/teamesyfo-github-actions-workflows/actions/setup-pnpm@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          node-version: 24.x
      - name: Build application
        run: pnpm run build
      - name: cache workspace
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}

      - name: Build and push docker image
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: nais/docker-build-push@87f920b0411b987d9a1fd4113aa384e1e3b54f2c
        id: docker-build-push
        with:
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-demo:
    name: Deploy to demo dev-gcp
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-demo.yaml
          VAR: image=${{ needs.build.outputs.image }}
